### ISSUE TITLE
Simple Shipping checkout styling required

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#79]
Just styles are missing for the simple shipping plugin on the checkout page:

<img width="916" alt="screenshot 2017-07-05 17 18 38" src="https://user-images.githubusercontent.com/22668877/27874045-11922c62-61a6-11e7-9988-49f8b73a4dba.png">

**Comment by amdrew** [comment]
Fixed!

**Comment by davidsherlock** [comment]
You missed one thing @amdrew:

![screenshot 2017-07-06 12 58 43](https://user-images.githubusercontent.com/22668877/27910109-9174e28a-624b-11e7-8e6a-b22c811ff004.png)

Cache was refreshed.

**Comment by amdrew** [comment]
👍

**Comment by amdrew** [comment]
@davidsherlock Try that

**Comment by davidsherlock** [comment]
Fixed @amdrew!

**Comment by amdrew** [comment]
Nice
